server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: Ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: ltt4456
    password: password

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 100000000
    refreshTokenExpiration: 604800

stripe:
  secretKey: ${STRIPE_SECRET_KEY}

websiteUrl: http://localhost:3000
